set -g prefix C-SPACE
set -g set-clipboard on

set -g default-terminal "tmux-256color"
set -sg terminal-overrides "*:RGB"
# set-option -ga terminal-features ",alacritty:usstyle"
set-option -ga terminal-features ",*:usstyle"

set -g base-index 1
set -g automatic-rename on
set -g renumber-windows on

set -g mode-keys vi

set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=blue bold"
set -g status-right ""
set -g status-left "#S"

# set-hook -g client-session-changed \
#   'run-shell "if [ -z \"$(tmux show-environment -g _tsh_skip_add 2>/dev/null)\" ]; then tmux-session-history add #{session_name}; else tmux set-environment -gu _tsh_skip_add; fi"'

bind r source-file "~/.config/tmux/tmux.conf" \; display 'tmux.conf sourced'
# bind o run-shell "tmux-session-history back"
# bind i run-shell "tmux-session-history forward"
bind f run-shell "tmux display-popup -E -w 80% -h 80% -T 'Session Picker' 'tmux-sessionizer'"
bind j run-shell "tmux display-popup -E -w 80% -h 80% -T 'Jira Picker' 'jira-fzf'"
bind V run-shell "tmux-sessionizer ~/videos"
bind I run-shell "tmux-sessionizer ~/images"
bind N run-shell "tmux-sessionizer ~/notes"
bind P run-shell "tmux-sessionizer ~/projects/personal"
bind D run-shell "tmux-sessionizer ~/.config"
bind H run-shell "tmux-sessionizer ~"
bind G run-shell "branch-note"
bind g run-shell "peek-note"
bind b run-shell "open-doc"
bind m run-shell "select-movie"
bind y run-shell "select-youtube"

# -- undercurl support
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'
